name: cicd_prdt

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

on: [workflow_dispatch]

env:
  PROJECT_NAME: ucarlike
  AWS_REGION: ap-northeast-2
  S3_BUCKET: ramses-cicd
  CODE_DEPLOY_APPLICATION_NAME: ramses-ucarlike
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: ramses-ucarlike-prdt

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    # (1) 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v4

    # (2) JDK 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=${{env.S3_BUCKET}},key=${{env.S3_FOLDER}}/${{env.ZIP_FILE}}.zip,bundleType=zip   
